######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 14 10:03:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += blackjack.h card.h deck.h hand.h handview.h
SOURCES += blackjack.cpp card.cpp deck.cpp hand.cpp handview.cpp main.cpp
RESOURCES += Blackjack.qrc
