#############################################################################
# Makefile for building: Blackjack
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat Sep 14 10:03:16 2013
# Project:  Blackjack.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile Blackjack.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = blackjack.cpp \
		card.cpp \
		deck.cpp \
		hand.cpp \
		handview.cpp \
		main.cpp moc_blackjack.cpp \
		moc_card.cpp \
		moc_hand.cpp \
		moc_handview.cpp \
		qrc_Blackjack.cpp
OBJECTS       = blackjack.o \
		card.o \
		deck.o \
		hand.o \
		handview.o \
		main.o \
		moc_blackjack.o \
		moc_card.o \
		moc_hand.o \
		moc_handview.o \
		qrc_Blackjack.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Blackjack.pro
QMAKE_TARGET  = Blackjack
DESTDIR       = 
TARGET        = Blackjack

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Blackjack.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Blackjack.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Blackjack.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Blackjack1.0.0 || $(MKDIR) .tmp/Blackjack1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Blackjack1.0.0/ && $(COPY_FILE) --parents blackjack.h card.h deck.h hand.h handview.h .tmp/Blackjack1.0.0/ && $(COPY_FILE) --parents Blackjack.qrc .tmp/Blackjack1.0.0/ && $(COPY_FILE) --parents blackjack.cpp card.cpp deck.cpp hand.cpp handview.cpp main.cpp .tmp/Blackjack1.0.0/ && (cd `dirname .tmp/Blackjack1.0.0` && $(TAR) Blackjack1.0.0.tar Blackjack1.0.0 && $(COMPRESS) Blackjack1.0.0.tar) && $(MOVE) `dirname .tmp/Blackjack1.0.0`/Blackjack1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Blackjack1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_blackjack.cpp moc_card.cpp moc_hand.cpp moc_handview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_blackjack.cpp moc_card.cpp moc_hand.cpp moc_handview.cpp
moc_blackjack.cpp: card.h \
		deck.h \
		hand.h \
		handview.h \
		blackjack.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) blackjack.h -o moc_blackjack.cpp

moc_card.cpp: card.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) card.h -o moc_card.cpp

moc_hand.cpp: card.h \
		hand.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) hand.h -o moc_hand.cpp

moc_handview.cpp: hand.h \
		card.h \
		handview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) handview.h -o moc_handview.cpp

compiler_rcc_make_all: qrc_Blackjack.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Blackjack.cpp
qrc_Blackjack.cpp: Blackjack.qrc \
		images/chip25.png \
		images/dealer_18.jpg \
		images/new.png \
		images/bg.jpg \
		images/clearbet.png \
		images/quit.png \
		images/dealer_15.jpg \
		images/chip5.png \
		images/chip50.png \
		images/cards/5h.png \
		images/cards/4d.png \
		images/cards/7c.png \
		images/cards/6s.png \
		images/cards/ah.png \
		images/cards/ts.png \
		images/cards/2c.png \
		images/cards/8h.png \
		images/cards/7d.png \
		images/cards/9s.png \
		images/cards/js.png \
		images/cards/kc.png \
		images/cards/3h.png \
		images/cards/2d.png \
		images/cards/5c.png \
		images/cards/4s.png \
		images/cards/qh.png \
		images/cards/ac.png \
		images/cards/kd.png \
		images/cards/6h.png \
		images/cards/5d.png \
		images/cards/7s.png \
		images/cards/8c.png \
		images/cards/th.png \
		images/cards/3c.png \
		images/cards/2s.png \
		images/cards/ad.png \
		images/cards/qc.png \
		images/cards/9h.png \
		images/cards/jh.png \
		images/cards/8d.png \
		images/cards/ks.png \
		images/cards/4h.png \
		images/cards/3d.png \
		images/cards/6c.png \
		images/cards/5s.png \
		images/cards/qd.png \
		images/cards/tc.png \
		images/cards/as.png \
		images/cards/7h.png \
		images/cards/6d.png \
		images/cards/9c.png \
		images/cards/8s.png \
		images/cards/jc.png \
		images/cards/2h.png \
		images/cards/td.png \
		images/cards/4c.png \
		images/cards/3s.png \
		images/cards/qs.png \
		images/cards/9d.png \
		images/cards/kh.png \
		images/cards/cb.png \
		images/cards/jd.png
	/usr/bin/rcc -name Blackjack Blackjack.qrc -o qrc_Blackjack.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

blackjack.o: blackjack.cpp blackjack.h \
		card.h \
		deck.h \
		hand.h \
		handview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blackjack.o blackjack.cpp

card.o: card.cpp card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o card.o card.cpp

deck.o: deck.cpp deck.h \
		card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o deck.o deck.cpp

hand.o: hand.cpp hand.h \
		card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hand.o hand.cpp

handview.o: handview.cpp handview.h \
		hand.h \
		card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o handview.o handview.cpp

main.o: main.cpp blackjack.h \
		card.h \
		deck.h \
		hand.h \
		handview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_blackjack.o: moc_blackjack.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_blackjack.o moc_blackjack.cpp

moc_card.o: moc_card.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_card.o moc_card.cpp

moc_hand.o: moc_hand.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hand.o moc_hand.cpp

moc_handview.o: moc_handview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_handview.o moc_handview.cpp

qrc_Blackjack.o: qrc_Blackjack.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Blackjack.o qrc_Blackjack.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

